# My variables
name: Yee Vien Ng
description: My github page

# Site settings
title: Yee Vien's portfolio
email: yvien90gmail.com

#logo: /assets/img/logo.png
#show_downloads: true
#google_analytics:
theme: jekyll-theme-cayman
