# Site settings
title: Yee Vien's portfolio
description: My github page
email: yvien90gmail.com

#logo: /assets/img/logo.png
#show_downloads: true
#google_analytics:
theme: jekyll-theme-cayman

#
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      comments: false
      

# Navigation pages
nav_pages:
  #- index.html
  - about.md
  
  
  #urls
  github:
    about_url: https://yvien226.github.io/aboutme.html
