# Site settings
title: Yee Vien's portfolio
description: My github page
email: yvien90gmail.com

#logo: /assets/img/logo.png
#show_downloads: true
#google_analytics:
theme: jekyll-theme-cayman

#
defaults:
  - scope:
      path: ""
    values:
      layout: default
