title: Yee Vien's Portfolio
description: Data Science | Machine Learning | Data Analytics | Data Visualisation | Optimisation
email: yvien90gmail.com
show_downloads: true
google_analytics: G-D4GBC2ETFV
theme: jekyll-theme-cayman

# socia media links
github_username: yvien226
linkedin_username: yeevienng
      
github:
  is_project_page: true
  home_url: ./
  contact_url: ./contact.html
  about_url: ./aboutme.html
